import { defineConfig } from 'astro/config';
import tailwind from '@astrojs/tailwind';
import sitemap from '@astrojs/sitemap';

// https://astro.build/config
export default defineConfig({
  site: 'https://enduranceaventure.com',
  integrations: [
    tailwind(),
    sitemap({
      filter: (page) => !page.includes('/raw_api/'),
    }),
  ],
  redirects: {
    // Redirects to official event websites
    '/gbc500_temp': 'https://gbc500.com',
    '/gbc500_temp/': 'https://gbc500.com',
    '/gravelbike': 'https://gbc500.com',
    '/gravelbike/': 'https://gbc500.com',
    '/gbc500-suivi-temps-reel': 'https://gbc500.com',
    '/gbc500-suivi-temps-reel/': 'https://gbc500.com',
    '/gbc500-confirmation-dinscription': 'https://gbc500.com',
    '/evenements/raids': 'https://raidtemiscamingue.ca',
    '/evenements/raids/': 'https://raidtemiscamingue.ca',
    '/rit-temp': 'https://raidtemiscamingue.ca',
    '/rit-temp/': 'https://raidtemiscamingue.ca',
    '/contactez-nous': '/contact',
    '/contactez-nous/': '/contact',

    // Old WordPress post paths with /non-classifiee/ or /nouveaux-evenements/
    '/non-classifiee/nouvelles-novembre-2023': '/nouvelles/nouvelles-novembre-2023',
    '/non-classifiee/nouvelles-novembre-2023/': '/nouvelles/nouvelles-novembre-2023',
    '/non-classifiee/nouvelles-octobre-2023': '/nouvelles/nouvelles-octobre-2023',
    '/non-classifiee/nouvelles-octobre-2023/': '/nouvelles/nouvelles-octobre-2023',
    '/non-classifiee/nouvelles-aout-2023': '/nouvelles/nouvelles-aout-2023',
    '/non-classifiee/nouvelles-aout-2023/': '/nouvelles/nouvelles-aout-2023',
    '/non-classifiee/nouvelles-avril-2023': '/nouvelles/nouvelles-avril-2023',
    '/non-classifiee/nouvelles-avril-2023/': '/nouvelles/nouvelles-avril-2023',
    '/non-classifiee/nouvelles-mars-2023': '/nouvelles/nouvelles-mars-2023',
    '/non-classifiee/nouvelles-mars-2023/': '/nouvelles/nouvelles-mars-2023',
    '/non-classifiee/nouvelles-fevrier-2023': '/nouvelles/nouvelles-fevrier-2023',
    '/non-classifiee/nouvelles-fevrier-2023/': '/nouvelles/nouvelles-fevrier-2023',
    '/non-classifiee/nouvelles-novembre-2022': '/nouvelles/nouvelles-novembre-2022',
    '/non-classifiee/nouvelles-novembre-2022/': '/nouvelles/nouvelles-novembre-2022',
    '/non-classifiee/nouvelles-20-juillet-2022': '/nouvelles/nouvelles-20-juillet-2022',
    '/non-classifiee/nouvelles-20-juillet-2022/': '/nouvelles/nouvelles-20-juillet-2022',
    '/non-classifiee/nouvelles-dhiver-2022': '/nouvelles/nouvelles-dhiver-2022',
    '/non-classifiee/nouvelles-dhiver-2022/': '/nouvelles/nouvelles-dhiver-2022',
    '/non-classifiee/hebergement-a-magog': '/nouvelles/hebergement-a-magog',
    '/non-classifiee/hebergement-a-magog/': '/nouvelles/hebergement-a-magog',
    '/non-classifiee/report-du-canada-man-woman-au-2-et-3-octobre-2021': '/nouvelles/report-du-canada-man-woman-au-2-et-3-octobre-2021',
    '/non-classifiee/report-du-canada-man-woman-au-2-et-3-octobre-2021/': '/nouvelles/report-du-canada-man-woman-au-2-et-3-octobre-2021',
    '/non-classifiee/gbc500-2021-parcours-bientot-pret': '/nouvelles/gbc500-2021-parcours-bientot-pret',
    '/non-classifiee/gbc500-2021-parcours-bientot-pret/': '/nouvelles/gbc500-2021-parcours-bientot-pret',
    '/nouveaux-evenements/nouveau-raid-endurance-aventure-temiscamingue-3-octobre-2020': '/nouvelles/nouveau-raid-endurance-aventure-temiscamingue-3-octobre-2020',
    '/nouveaux-evenements/nouveau-raid-endurance-aventure-temiscamingue-3-octobre-2020/': '/nouvelles/nouveau-raid-endurance-aventure-temiscamingue-3-octobre-2020',
    '/nouveaux-evenements/gbc-500-mission-accomplie': '/nouvelles/gbc-500-mission-accomplie',
    '/nouveaux-evenements/gbc-500-mission-accomplie/': '/nouvelles/gbc-500-mission-accomplie',
    '/nouveaux-evenements/nouvel-evenement-cet-ete-le-gravel-bikepacking-challenge-500': '/nouvelles/nouvel-evenement-cet-ete-le-gravel-bikepacking-challenge-500',
    '/nouveaux-evenements/nouvel-evenement-cet-ete-le-gravel-bikepacking-challenge-500/': '/nouvelles/nouvel-evenement-cet-ete-le-gravel-bikepacking-challenge-500',
    '/non-classifiee/endurance-aventure-2020': '/nouvelles/endurance-aventure-2020',
    '/non-classifiee/endurance-aventure-2020/': '/nouvelles/endurance-aventure-2020',
    '/non-classifiee/canada-man-woman-1-epic-race-triathlon-in-canada': '/nouvelles/canada-man-woman-1-epic-race-triathlon-in-canada',
    '/non-classifiee/canada-man-woman-1-epic-race-triathlon-in-canada/': '/nouvelles/canada-man-woman-1-epic-race-triathlon-in-canada',
    '/non-classifiee/velo-cafe-ouvert-7-jours-7': '/nouvelles/velo-cafe-ouvert-7-jours-7',
    '/non-classifiee/velo-cafe-ouvert-7-jours-7/': '/nouvelles/velo-cafe-ouvert-7-jours-7',
    '/non-classifiee/raid-international-gaspesie-inscriptions-ouvertes': '/nouvelles/raid-international-gaspesie-inscriptions-ouvertes',
    '/non-classifiee/raid-international-gaspesie-inscriptions-ouvertes/': '/nouvelles/raid-international-gaspesie-inscriptions-ouvertes',
    '/non-classifiee/grande-premiere-de-lemission-canada-man-woman-2018-tv-show-premiere': '/nouvelles/grande-premiere-de-lemission-canada-man-woman-2018-tv-show-premiere',
    '/non-classifiee/grande-premiere-de-lemission-canada-man-woman-2018-tv-show-premiere/': '/nouvelles/grande-premiere-de-lemission-canada-man-woman-2018-tv-show-premiere',
    '/non-classifiee/inscriptions-au-canadaman-woman-lac-megantic-xtri-world-tour': '/nouvelles/inscriptions-au-canadaman-woman-lac-megantic-xtri-world-tour',
    '/non-classifiee/inscriptions-au-canadaman-woman-lac-megantic-xtri-world-tour/': '/nouvelles/inscriptions-au-canadaman-woman-lac-megantic-xtri-world-tour',
    '/non-classifiee/raid-international-gaspesie-6-7-8-9-septembre-2018': '/nouvelles/raid-international-gaspesie-6-7-8-9-septembre-2018',
    '/non-classifiee/raid-international-gaspesie-6-7-8-9-septembre-2018/': '/nouvelles/raid-international-gaspesie-6-7-8-9-septembre-2018',
    '/non-classifiee/invitation-film-canada-man-woman-2017': '/nouvelles/invitation-film-canada-man-woman-2017',
    '/non-classifiee/invitation-film-canada-man-woman-2017/': '/nouvelles/invitation-film-canada-man-woman-2017',
    '/non-classifiee/trail-de-neiges-2018': '/nouvelles/trail-de-neiges-2018',
    '/non-classifiee/trail-de-neiges-2018/': '/nouvelles/trail-de-neiges-2018',
    '/non-classifiee/en-preparation-pour-votre-prochaine-aventure-avec-endurance-aventure': '/nouvelles/en-preparation-pour-votre-prochaine-aventure-avec-endurance-aventure',
    '/non-classifiee/en-preparation-pour-votre-prochaine-aventure-avec-endurance-aventure/': '/nouvelles/en-preparation-pour-votre-prochaine-aventure-avec-endurance-aventure',
    '/non-classifiee/lannee-2018-sannonce-bien-remplie-chez-endurance-aventure': '/nouvelles/lannee-2018-sannonce-bien-remplie-chez-endurance-aventure',
    '/non-classifiee/lannee-2018-sannonce-bien-remplie-chez-endurance-aventure/': '/nouvelles/lannee-2018-sannonce-bien-remplie-chez-endurance-aventure',
  },
});
